export interface CountryData {
  code: string;
  name: string;
  phoneCode: string;
  currency: string;
  currencySymbol: string;
}

export const countries: CountryData[] = [
  { code: "AF", name: "Afghanistan", phoneCode: "+93", currency: "AFN", currencySymbol: "؋" },
  { code: "AL", name: "Albania", phoneCode: "+355", currency: "ALL", currencySymbol: "L" },
  { code: "DZ", name: "Algeria", phoneCode: "+213", currency: "DZD", currencySymbol: "د.ج" },
  { code: "AD", name: "Andorra", phoneCode: "+376", currency: "EUR", currencySymbol: "€" },
  { code: "AO", name: "Angola", phoneCode: "+244", currency: "AOA", currencySymbol: "Kz" },
  { code: "AG", name: "Antigua and Barbuda", phoneCode: "+1-268", currency: "XCD", currencySymbol: "$" },
  { code: "AR", name: "Argentina", phoneCode: "+54", currency: "ARS", currencySymbol: "$" },
  { code: "AM", name: "Armenia", phoneCode: "+374", currency: "AMD", currencySymbol: "֏" },
  { code: "AU", name: "Australia", phoneCode: "+61", currency: "AUD", currencySymbol: "A$" },
  { code: "AT", name: "Austria", phoneCode: "+43", currency: "EUR", currencySymbol: "€" },
  { code: "AZ", name: "Azerbaijan", phoneCode: "+994", currency: "AZN", currencySymbol: "₼" },
  { code: "BS", name: "Bahamas", phoneCode: "+1-242", currency: "BSD", currencySymbol: "B$" },
  { code: "BH", name: "Bahrain", phoneCode: "+973", currency: "BHD", currencySymbol: ".د.ب" },
  { code: "BD", name: "Bangladesh", phoneCode: "+880", currency: "BDT", currencySymbol: "৳" },
  { code: "BB", name: "Barbados", phoneCode: "+1-246", currency: "BBD", currencySymbol: "Bds$" },
  { code: "BY", name: "Belarus", phoneCode: "+375", currency: "BYN", currencySymbol: "Br" },
  { code: "BE", name: "Belgium", phoneCode: "+32", currency: "EUR", currencySymbol: "€" },
  { code: "BZ", name: "Belize", phoneCode: "+501", currency: "BZD", currencySymbol: "BZ$" },
  { code: "BJ", name: "Benin", phoneCode: "+229", currency: "XOF", currencySymbol: "CFA" },
  { code: "BT", name: "Bhutan", phoneCode: "+975", currency: "BTN", currencySymbol: "Nu." },
  { code: "BO", name: "Bolivia", phoneCode: "+591", currency: "BOB", currencySymbol: "Bs." },
  { code: "BA", name: "Bosnia and Herzegovina", phoneCode: "+387", currency: "BAM", currencySymbol: "KM" },
  { code: "BW", name: "Botswana", phoneCode: "+267", currency: "BWP", currencySymbol: "P" },
  { code: "BR", name: "Brazil", phoneCode: "+55", currency: "BRL", currencySymbol: "R$" },
  { code: "BN", name: "Brunei", phoneCode: "+673", currency: "BND", currencySymbol: "B$" },
  { code: "BG", name: "Bulgaria", phoneCode: "+359", currency: "BGN", currencySymbol: "лв" },
  { code: "BF", name: "Burkina Faso", phoneCode: "+226", currency: "XOF", currencySymbol: "CFA" },
  { code: "BI", name: "Burundi", phoneCode: "+257", currency: "BIF", currencySymbol: "FBu" },
  { code: "KH", name: "Cambodia", phoneCode: "+855", currency: "KHR", currencySymbol: "៛" },
  { code: "CM", name: "Cameroon", phoneCode: "+237", currency: "XAF", currencySymbol: "FCFA" },
  { code: "CA", name: "Canada", phoneCode: "+1", currency: "CAD", currencySymbol: "CA$" },
  { code: "CV", name: "Cape Verde", phoneCode: "+238", currency: "CVE", currencySymbol: "Esc" },
  { code: "CF", name: "Central African Republic", phoneCode: "+236", currency: "XAF", currencySymbol: "FCFA" },
  { code: "TD", name: "Chad", phoneCode: "+235", currency: "XAF", currencySymbol: "FCFA" },
  { code: "CL", name: "Chile", phoneCode: "+56", currency: "CLP", currencySymbol: "CLP$" },
  { code: "CN", name: "China", phoneCode: "+86", currency: "CNY", currencySymbol: "¥" },
  { code: "CO", name: "Colombia", phoneCode: "+57", currency: "COP", currencySymbol: "COL$" },
  { code: "KM", name: "Comoros", phoneCode: "+269", currency: "KMF", currencySymbol: "CF" },
  { code: "CG", name: "Congo", phoneCode: "+242", currency: "XAF", currencySymbol: "FCFA" },
  { code: "CD", name: "Congo (DRC)", phoneCode: "+243", currency: "CDF", currencySymbol: "FC" },
  { code: "CR", name: "Costa Rica", phoneCode: "+506", currency: "CRC", currencySymbol: "₡" },
  { code: "CI", name: "Côte d'Ivoire", phoneCode: "+225", currency: "XOF", currencySymbol: "CFA" },
  { code: "HR", name: "Croatia", phoneCode: "+385", currency: "EUR", currencySymbol: "€" },
  { code: "CU", name: "Cuba", phoneCode: "+53", currency: "CUP", currencySymbol: "₱" },
  { code: "CY", name: "Cyprus", phoneCode: "+357", currency: "EUR", currencySymbol: "€" },
  { code: "CZ", name: "Czech Republic", phoneCode: "+420", currency: "CZK", currencySymbol: "Kč" },
  { code: "DK", name: "Denmark", phoneCode: "+45", currency: "DKK", currencySymbol: "kr" },
  { code: "DJ", name: "Djibouti", phoneCode: "+253", currency: "DJF", currencySymbol: "Fdj" },
  { code: "DM", name: "Dominica", phoneCode: "+1-767", currency: "XCD", currencySymbol: "$" },
  { code: "DO", name: "Dominican Republic", phoneCode: "+1-809", currency: "DOP", currencySymbol: "RD$" },
  { code: "EC", name: "Ecuador", phoneCode: "+593", currency: "USD", currencySymbol: "$" },
  { code: "EG", name: "Egypt", phoneCode: "+20", currency: "EGP", currencySymbol: "E£" },
  { code: "SV", name: "El Salvador", phoneCode: "+503", currency: "USD", currencySymbol: "$" },
  { code: "GQ", name: "Equatorial Guinea", phoneCode: "+240", currency: "XAF", currencySymbol: "FCFA" },
  { code: "ER", name: "Eritrea", phoneCode: "+291", currency: "ERN", currencySymbol: "Nfk" },
  { code: "EE", name: "Estonia", phoneCode: "+372", currency: "EUR", currencySymbol: "€" },
  { code: "SZ", name: "Eswatini", phoneCode: "+268", currency: "SZL", currencySymbol: "E" },
  { code: "ET", name: "Ethiopia", phoneCode: "+251", currency: "ETB", currencySymbol: "Br" },
  { code: "FJ", name: "Fiji", phoneCode: "+679", currency: "FJD", currencySymbol: "FJ$" },
  { code: "FI", name: "Finland", phoneCode: "+358", currency: "EUR", currencySymbol: "€" },
  { code: "FR", name: "France", phoneCode: "+33", currency: "EUR", currencySymbol: "€" },
  { code: "GA", name: "Gabon", phoneCode: "+241", currency: "XAF", currencySymbol: "FCFA" },
  { code: "GM", name: "Gambia", phoneCode: "+220", currency: "GMD", currencySymbol: "D" },
  { code: "GE", name: "Georgia", phoneCode: "+995", currency: "GEL", currencySymbol: "₾" },
  { code: "DE", name: "Germany", phoneCode: "+49", currency: "EUR", currencySymbol: "€" },
  { code: "GH", name: "Ghana", phoneCode: "+233", currency: "GHS", currencySymbol: "GH₵" },
  { code: "GR", name: "Greece", phoneCode: "+30", currency: "EUR", currencySymbol: "€" },
  { code: "GD", name: "Grenada", phoneCode: "+1-473", currency: "XCD", currencySymbol: "$" },
  { code: "GT", name: "Guatemala", phoneCode: "+502", currency: "GTQ", currencySymbol: "Q" },
  { code: "GN", name: "Guinea", phoneCode: "+224", currency: "GNF", currencySymbol: "GFr" },
  { code: "GW", name: "Guinea-Bissau", phoneCode: "+245", currency: "XOF", currencySymbol: "CFA" },
  { code: "GY", name: "Guyana", phoneCode: "+592", currency: "GYD", currencySymbol: "GY$" },
  { code: "HT", name: "Haiti", phoneCode: "+509", currency: "HTG", currencySymbol: "G" },
  { code: "HN", name: "Honduras", phoneCode: "+504", currency: "HNL", currencySymbol: "L" },
  { code: "HK", name: "Hong Kong", phoneCode: "+852", currency: "HKD", currencySymbol: "HK$" },
  { code: "HU", name: "Hungary", phoneCode: "+36", currency: "HUF", currencySymbol: "Ft" },
  { code: "IS", name: "Iceland", phoneCode: "+354", currency: "ISK", currencySymbol: "kr" },
  { code: "IN", name: "India", phoneCode: "+91", currency: "INR", currencySymbol: "₹" },
  { code: "ID", name: "Indonesia", phoneCode: "+62", currency: "IDR", currencySymbol: "Rp" },
  { code: "IR", name: "Iran", phoneCode: "+98", currency: "IRR", currencySymbol: "﷼" },
  { code: "IQ", name: "Iraq", phoneCode: "+964", currency: "IQD", currencySymbol: "ع.د" },
  { code: "IE", name: "Ireland", phoneCode: "+353", currency: "EUR", currencySymbol: "€" },
  { code: "IL", name: "Israel", phoneCode: "+972", currency: "ILS", currencySymbol: "₪" },
  { code: "IT", name: "Italy", phoneCode: "+39", currency: "EUR", currencySymbol: "€" },
  { code: "JM", name: "Jamaica", phoneCode: "+1-876", currency: "JMD", currencySymbol: "J$" },
  { code: "JP", name: "Japan", phoneCode: "+81", currency: "JPY", currencySymbol: "¥" },
  { code: "JO", name: "Jordan", phoneCode: "+962", currency: "JOD", currencySymbol: "د.ا" },
  { code: "KZ", name: "Kazakhstan", phoneCode: "+7", currency: "KZT", currencySymbol: "₸" },
  { code: "KE", name: "Kenya", phoneCode: "+254", currency: "KES", currencySymbol: "KSh" },
  { code: "KI", name: "Kiribati", phoneCode: "+686", currency: "AUD", currencySymbol: "A$" },
  { code: "KP", name: "North Korea", phoneCode: "+850", currency: "KPW", currencySymbol: "₩" },
  { code: "KR", name: "South Korea", phoneCode: "+82", currency: "KRW", currencySymbol: "₩" },
  { code: "KW", name: "Kuwait", phoneCode: "+965", currency: "KWD", currencySymbol: "د.ك" },
  { code: "KG", name: "Kyrgyzstan", phoneCode: "+996", currency: "KGS", currencySymbol: "сом" },
  { code: "LA", name: "Laos", phoneCode: "+856", currency: "LAK", currencySymbol: "₭" },
  { code: "LV", name: "Latvia", phoneCode: "+371", currency: "EUR", currencySymbol: "€" },
  { code: "LB", name: "Lebanon", phoneCode: "+961", currency: "LBP", currencySymbol: "ل.ل" },
  { code: "LS", name: "Lesotho", phoneCode: "+266", currency: "LSL", currencySymbol: "L" },
  { code: "LR", name: "Liberia", phoneCode: "+231", currency: "LRD", currencySymbol: "L$" },
  { code: "LY", name: "Libya", phoneCode: "+218", currency: "LYD", currencySymbol: "ل.د" },
  { code: "LI", name: "Liechtenstein", phoneCode: "+423", currency: "CHF", currencySymbol: "CHf" },
  { code: "LT", name: "Lithuania", phoneCode: "+370", currency: "EUR", currencySymbol: "€" },
  { code: "LU", name: "Luxembourg", phoneCode: "+352", currency: "EUR", currencySymbol: "€" },
  { code: "MG", name: "Madagascar", phoneCode: "+261", currency: "MGA", currencySymbol: "Ar" },
  { code: "MW", name: "Malawi", phoneCode: "+265", currency: "MWK", currencySymbol: "MK" },
  { code: "MY", name: "Malaysia", phoneCode: "+60", currency: "MYR", currencySymbol: "RM" },
  { code: "MV", name: "Maldives", phoneCode: "+960", currency: "MVR", currencySymbol: "Rf" },
  { code: "ML", name: "Mali", phoneCode: "+223", currency: "XOF", currencySymbol: "CFA" },
  { code: "MT", name: "Malta", phoneCode: "+356", currency: "EUR", currencySymbol: "€" },
  { code: "MH", name: "Marshall Islands", phoneCode: "+692", currency: "USD", currencySymbol: "$" },
  { code: "MR", name: "Mauritania", phoneCode: "+222", currency: "MRU", currencySymbol: "UM" },
  { code: "MU", name: "Mauritius", phoneCode: "+230", currency: "MUR", currencySymbol: "₨" },
  { code: "MX", name: "Mexico", phoneCode: "+52", currency: "MXN", currencySymbol: "Mex$" },
  { code: "FM", name: "Micronesia", phoneCode: "+691", currency: "USD", currencySymbol: "$" },
  { code: "MD", name: "Moldova", phoneCode: "+373", currency: "MDL", currencySymbol: "L" },
  { code: "MC", name: "Monaco", phoneCode: "+377", currency: "EUR", currencySymbol: "€" },
  { code: "MN", name: "Mongolia", phoneCode: "+976", currency: "MNT", currencySymbol: "₮" },
  { code: "ME", name: "Montenegro", phoneCode: "+382", currency: "EUR", currencySymbol: "€" },
  { code: "MA", name: "Morocco", phoneCode: "+212", currency: "MAD", currencySymbol: "د.م." },
  { code: "MZ", name: "Mozambique", phoneCode: "+258", currency: "MZN", currencySymbol: "MT" },
  { code: "MM", name: "Myanmar", phoneCode: "+95", currency: "MMK", currencySymbol: "K" },
  { code: "NA", name: "Namibia", phoneCode: "+264", currency: "NAD", currencySymbol: "N$" },
  { code: "NR", name: "Nauru", phoneCode: "+674", currency: "AUD", currencySymbol: "A$" },
  { code: "NP", name: "Nepal", phoneCode: "+977", currency: "NPR", currencySymbol: "₨" },
  { code: "NL", name: "Netherlands", phoneCode: "+31", currency: "EUR", currencySymbol: "€" },
  { code: "NZ", name: "New Zealand", phoneCode: "+64", currency: "NZD", currencySymbol: "NZ$" },
  { code: "NI", name: "Nicaragua", phoneCode: "+505", currency: "NIO", currencySymbol: "C$" },
  { code: "NE", name: "Niger", phoneCode: "+227", currency: "XOF", currencySymbol: "CFA" },
  { code: "NG", name: "Nigeria", phoneCode: "+234", currency: "NGN", currencySymbol: "₦" },
  { code: "MK", name: "North Macedonia", phoneCode: "+389", currency: "MKD", currencySymbol: "ден" },
  { code: "NO", name: "Norway", phoneCode: "+47", currency: "NOK", currencySymbol: "kr" },
  { code: "OM", name: "Oman", phoneCode: "+968", currency: "OMR", currencySymbol: "﷼" },
  { code: "PK", name: "Pakistan", phoneCode: "+92", currency: "PKR", currencySymbol: "₨" },
  { code: "PW", name: "Palau", phoneCode: "+680", currency: "USD", currencySymbol: "$" },
  { code: "PS", name: "Palestine", phoneCode: "+970", currency: "ILS", currencySymbol: "₪" },
  { code: "PA", name: "Panama", phoneCode: "+507", currency: "PAB", currencySymbol: "B/." },
  { code: "PG", name: "Papua New Guinea", phoneCode: "+675", currency: "PGK", currencySymbol: "K" },
  { code: "PY", name: "Paraguay", phoneCode: "+595", currency: "PYG", currencySymbol: "₲" },
  { code: "PE", name: "Peru", phoneCode: "+51", currency: "PEN", currencySymbol: "S/." },
  { code: "PH", name: "Philippines", phoneCode: "+63", currency: "PHP", currencySymbol: "₱" },
  { code: "PL", name: "Poland", phoneCode: "+48", currency: "PLN", currencySymbol: "zł" },
  { code: "PT", name: "Portugal", phoneCode: "+351", currency: "EUR", currencySymbol: "€" },
  { code: "QA", name: "Qatar", phoneCode: "+974", currency: "QAR", currencySymbol: "ر.ق" },
  { code: "RO", name: "Romania", phoneCode: "+40", currency: "RON", currencySymbol: "lei" },
  { code: "RU", name: "Russia", phoneCode: "+7", currency: "RUB", currencySymbol: "₽" },
  { code: "RW", name: "Rwanda", phoneCode: "+250", currency: "RWF", currencySymbol: "FRw" },
  { code: "KN", name: "Saint Kitts and Nevis", phoneCode: "+1-869", currency: "XCD", currencySymbol: "$" },
  { code: "LC", name: "Saint Lucia", phoneCode: "+1-758", currency: "XCD", currencySymbol: "$" },
  { code: "VC", name: "Saint Vincent and the Grenadines", phoneCode: "+1-784", currency: "XCD", currencySymbol: "$" },
  { code: "WS", name: "Samoa", phoneCode: "+685", currency: "WST", currencySymbol: "WS$" },
  { code: "SM", name: "San Marino", phoneCode: "+378", currency: "EUR", currencySymbol: "€" },
  { code: "ST", name: "São Tomé and Príncipe", phoneCode: "+239", currency: "STN", currencySymbol: "Db" },
  { code: "SA", name: "Saudi Arabia", phoneCode: "+966", currency: "SAR", currencySymbol: "﷼" },
  { code: "SN", name: "Senegal", phoneCode: "+221", currency: "XOF", currencySymbol: "CFA" },
  { code: "RS", name: "Serbia", phoneCode: "+381", currency: "RSD", currencySymbol: "дин" },
  { code: "SC", name: "Seychelles", phoneCode: "+248", currency: "SCR", currencySymbol: "SRe" },
  { code: "SL", name: "Sierra Leone", phoneCode: "+232", currency: "SLL", currencySymbol: "Le" },
  { code: "SG", name: "Singapore", phoneCode: "+65", currency: "SGD", currencySymbol: "S$" },
  { code: "SK", name: "Slovakia", phoneCode: "+421", currency: "EUR", currencySymbol: "€" },
  { code: "SI", name: "Slovenia", phoneCode: "+386", currency: "EUR", currencySymbol: "€" },
  { code: "SB", name: "Solomon Islands", phoneCode: "+677", currency: "SBD", currencySymbol: "SI$" },
  { code: "SO", name: "Somalia", phoneCode: "+252", currency: "SOS", currencySymbol: "Sh.So." },
  { code: "ZA", name: "South Africa", phoneCode: "+27", currency: "ZAR", currencySymbol: "R" },
  { code: "SS", name: "South Sudan", phoneCode: "+211", currency: "SSP", currencySymbol: "£" },
  { code: "ES", name: "Spain", phoneCode: "+34", currency: "EUR", currencySymbol: "€" },
  { code: "LK", name: "Sri Lanka", phoneCode: "+94", currency: "LKR", currencySymbol: "Rs" },
  { code: "SD", name: "Sudan", phoneCode: "+249", currency: "SDG", currencySymbol: "ج.س." },
  { code: "SR", name: "Suriname", phoneCode: "+597", currency: "SRD", currencySymbol: "$" },
  { code: "SE", name: "Sweden", phoneCode: "+46", currency: "SEK", currencySymbol: "kr" },
  { code: "CH", name: "Switzerland", phoneCode: "+41", currency: "CHF", currencySymbol: "CHf" },
  { code: "SY", name: "Syria", phoneCode: "+963", currency: "SYP", currencySymbol: "ل.س" },
  { code: "TW", name: "Taiwan", phoneCode: "+886", currency: "TWD", currencySymbol: "NT$" },
  { code: "TJ", name: "Tajikistan", phoneCode: "+992", currency: "TJS", currencySymbol: "SM" },
  { code: "TZ", name: "Tanzania", phoneCode: "+255", currency: "TZS", currencySymbol: "TSh" },
  { code: "TH", name: "Thailand", phoneCode: "+66", currency: "THB", currencySymbol: "฿" },
  { code: "TL", name: "Timor-Leste", phoneCode: "+670", currency: "USD", currencySymbol: "$" },
  { code: "TG", name: "Togo", phoneCode: "+228", currency: "XOF", currencySymbol: "CFA" },
  { code: "TO", name: "Tonga", phoneCode: "+676", currency: "TOP", currencySymbol: "T$" },
  { code: "TT", name: "Trinidad and Tobago", phoneCode: "+1-868", currency: "TTD", currencySymbol: "TT$" },
  { code: "TN", name: "Tunisia", phoneCode: "+216", currency: "TND", currencySymbol: "د.ت" },
  { code: "TR", name: "Turkey", phoneCode: "+90", currency: "TRY", currencySymbol: "₺" },
  { code: "TM", name: "Turkmenistan", phoneCode: "+993", currency: "TMT", currencySymbol: "T" },
  { code: "TV", name: "Tuvalu", phoneCode: "+688", currency: "AUD", currencySymbol: "A$" },
  { code: "UG", name: "Uganda", phoneCode: "+256", currency: "UGX", currencySymbol: "USh" },
  { code: "UA", name: "Ukraine", phoneCode: "+380", currency: "UAH", currencySymbol: "₴" },
  { code: "AE", name: "United Arab Emirates", phoneCode: "+971", currency: "AED", currencySymbol: "د.إ" },
  { code: "GB", name: "United Kingdom", phoneCode: "+44", currency: "GBP", currencySymbol: "£" },
  { code: "US", name: "United States", phoneCode: "+1", currency: "USD", currencySymbol: "$" },
  { code: "UY", name: "Uruguay", phoneCode: "+598", currency: "UYU", currencySymbol: "$U" },
  { code: "UZ", name: "Uzbekistan", phoneCode: "+998", currency: "UZS", currencySymbol: "so'm" },
  { code: "VU", name: "Vanuatu", phoneCode: "+678", currency: "VUV", currencySymbol: "VT" },
  { code: "VA", name: "Vatican City", phoneCode: "+379", currency: "EUR", currencySymbol: "€" },
  { code: "VE", name: "Venezuela", phoneCode: "+58", currency: "VES", currencySymbol: "Bs.S" },
  { code: "VN", name: "Vietnam", phoneCode: "+84", currency: "VND", currencySymbol: "₫" },
  { code: "YE", name: "Yemen", phoneCode: "+967", currency: "YER", currencySymbol: "﷼" },
  { code: "ZM", name: "Zambia", phoneCode: "+260", currency: "ZMW", currencySymbol: "ZK" },
  { code: "ZW", name: "Zimbabwe", phoneCode: "+263", currency: "ZWL", currencySymbol: "Z$" },
];

export function getCountryByCode(code: string): CountryData | undefined {
  return countries.find((c) => c.code === code);
}

export function getCountryCurrency(code: string): string | undefined {
  return getCountryByCode(code)?.currency;
}

export function getCountryCurrencySymbol(code: string): string | undefined {
  return getCountryByCode(code)?.currencySymbol;
}

export function getCountryPhoneCode(code: string): string | undefined {
  return getCountryByCode(code)?.phoneCode;
}

export function getCurrencySymbol(currencyCode: string): string {
  const country = countries.find((c) => c.currency === currencyCode);
  return country?.currencySymbol ?? currencyCode;
}